/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototiposmockups;

/**
 *
 * @author JULIANASOU
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        BrackgroundColor1 = new javax.swing.JPanel();
        GestaoFornecedor = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PainelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PainelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 66, 1070, 590));

        BrackgroundColor1.setBackground(new java.awt.Color(0, 0, 0));
        BrackgroundColor1.setForeground(new java.awt.Color(255, 255, 255));
        BrackgroundColor1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GestaoFornecedor.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        GestaoFornecedor.setForeground(new java.awt.Color(255, 255, 255));
        GestaoFornecedor.setText("Gestão de Fornecedores");
        BrackgroundColor1.add(GestaoFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 410, 50));

        usuario.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("usuário");
        BrackgroundColor1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototiposmockups/usuário232.PNG"))); // NOI18N
        BrackgroundColor1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, -1, 60));

        getContentPane().add(BrackgroundColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BrackgroundColor1;
    private javax.swing.JLabel GestaoFornecedor;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
